"""empty message

Revision ID: 472bb91c6dfc
Revises: 8b9c8b75fb82
Create Date: 2019-05-19 23:30:55.559399

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '472bb91c6dfc'
down_revision = '8b9c8b75fb82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Ledger', sa.Column('amount', sa.Float(), nullable=True))
    op.drop_column('Ledger', 'ammount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Ledger', sa.Column('ammount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('Ledger', 'amount')
    # ### end Alembic commands ###
