"""empty message

Revision ID: 8b9c8b75fb82
Revises: f963ab1f5eb7
Create Date: 2019-05-19 20:46:58.675210

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from models import Ledger

# revision identifiers, used by Alembic.
revision = '8b9c8b75fb82'
down_revision = 'f963ab1f5eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sqlalchemy_utils.types.choice.ChoiceType(Ledger.transaction_type_choices), nullable=True),
    sa.Column('ammount', sa.Float(), nullable=True),
    sa.Column('details', sqlalchemy_utils.types.choice.ChoiceType(Ledger.details_choices), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['Accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Ledger')
    # ### end Alembic commands ###
